export interface Listing{
    id: number;
    user_id: number;
    expiration: string;
    title: string;
    summary: string;
    description: string;
    keywords:  string[] | null;
    email: string;
    url: string;
    phone: string;
    address: string;
    complement: string;
    city: string;
    state: string;
    zipCode: string;
    status: string;
    plan: string;
    observation: string;
    facebook: string;
    instagram: string;
    linkedIn: string;
    openingHours: string;
    paymentId: number;
    logoImage: string;
    coverImage: string;
    payment: number;
    promotionalCode: string;
    freePlan: boolean;
    createdAt: string;
    updatedAt: string;
}